export const type = {
    ADD_TO_BASKET: "ADD_TO_BASKET",
    REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
    SET_USER: "SET_USER",
    // CHANGE_QUANTITY: "CHANGE_QUANTITY",
    // CLEAR_BASKET: "CLEAR_BASKET",
}